markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Rob Clark
url: http://rclark.info
description: A fantastic blog that is fantastic.
twitter: lojak
github: lojack
gravatar_url: http://www.gravatar.com/avatar/6b330538a13e9eca147322812cbdf3c7.png
